name: Destroy and Cleanup

on:
  workflow_dispatch: 

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
          terraform_wrapper: false

      - name: Initialize Terraform
        run: terraform init --reconfigure

      - name: Destroy Terraform Infrastructure
        run: terraform destroy --auto-approve || echo "Terraform state not found."

      - name: Remove Terraform State from S3
        run: |
          aws s3 rm s3://terraform-lightsail-state --recursive --region us-east-1 || echo "S3 bucket already empty."
          aws s3api delete-bucket --bucket terraform-lightsail-state --region us-east-1 || echo "S3 bucket already deleted."
          terraform state rm module.state_management.aws_s3_bucket.terraform_state || echo "State already removed."


